### ISSUE TITLE
Scrum Master cycle owns "THE HOW"?

### ISSUE THREAD

**Issue by shijopaul** [scrumatscale/official-guide#138]
After a good RSM or RPO class, the students are clear that the PO owns the "What" and the Developers owns the "How".
We have slides with the titles "The Product Owner Owns the What" and "The Developers Owns the HOW".

In the S@S, when we explain the PO cycle and talks about how they own "THE WHAT", as in the diagram. It goes well.

But when we explain the SM Cycle and talks about the "THE HOW" part in the diagram, it can create confusion.

While the intent is clear, it is better to clarify that the SM Cycle owns "THE TRANSFORMATION" or "Continuous Improvement". Or may be remove the "THE HOW" from the diagram?

Refer the diagram: https://www.scrumatscale.com/scrum-at-scale-guide-online/#the-components-of-scrumatscale

**Comment by scrumatscale** [comment]
Hi @shijopaul Appreciate the context. At one point we considered changing the name to the "Developer-Cycle" but decided against that because some components, e.g., "Impediment Removal" is not only related to the Developers. Similarly, "Cross-Team coordination" is about more than the "Transformation". In Scrum, the "How" refers specifically to how a thing/service is built by a team. In S@S, the "How" refers also to how the teams are structured and coordinated, which is about Scrum Mastery, and hence the "Scrum Master Cycle" 

At the moment, we still feel contrasting the "What" and the "how" to describe the separation of accountabilities is the most effective/simple way to convey the concept.
