### ISSUE TITLE
s@s: Is it a Meta-framework or the new SAFe?

### ISSUE THREAD

**Issue by MirkoKleiner** [scrumatscale/official-guide#48]
I'm a big fan of keeping S@S simple. Since the new vocabulary for some of the events (e.g. Scaled daily scrum) or roles (chief product owner), etc have been introduced I have the feeling s@s gets unnecessairly complicated and will confuse the attendees. E.g. for the backlog items we also don't  call them epics, features, user stories, etc. We call them backlog items and show an example how companies create a hierarchy and agree to common label. Making a long story short: I'd like to start a discussion about if it's not better to keep s@s a meta framework and add examples how events, roles, artifacts, etc have been labeled by companies while our classes or to the appendix of the guide.

cheers Mirko

**Comment by swisskauboy** [comment]
Totally agree on the "keeping it simple" principle. However, it is also important or at least very helpful when people are using the same terminology. Communication across companies and in the community will be easier if this terminology is universal.

I think in no way of S@S as "the new SAFe", but it could be made clearer what is left open to the "implementer" and what not (in order to still call it S@S). For instance, that S@S doesn't prescribe whether the Scrum of Scrums and Meta Scrum teams are virtual or actual teams is not really clear. I think this is one of the strengths of S@S - you can start off with virtual teams and make it an actual team if need be.

As for the example of the Chief Product Owner, I wouldn't mind removing that as a term, but it does make writing the S@S Guide harder if you can't refer to that role without defining a term for it.

**Comment by PaulaKvedaras** [comment]
In my opinion, Scrum@Scale is definitely NOT the new SAFE. 
S@S formalized how Scrum naturally scales in the simplest way. I think the new vocabulary comes to help us, and not to make things more complicated.. in fact not knowing how to name concepts, make them really more complicated. The role of Chief Product Owner has been very helpful in many of the organizations I know. 

At the end, I think we should read the Guide and each paragraph ask "Does it add value?". I have done the exercise, and my answer is YES. What is your answer?

**Comment by JoeJustice** [comment]
I support this motion Mirko, and appreciate your comment. Scrum is simple and effective, and therefore adopted and has stood the test of time to a point (25 years now). S@S may have an additional advantage to other scaling frameworks if it also stays simple and effective. I would love it to just be the same 3 roles, 5 events, and 3 outputs. if an initiative requires more than one teams, the teams sit next to each other. If it requires more than 5 teams, another scrum team may have the backlog of coordinating and releasing the aggregate product. If more than 5 of those are needed, then add another coordinating team. Who attends which coordinating team meeting is defined by sprint goal, and therefore can meet the mathematical constraints of a scale free architecture.
