### ISSUE TITLE
Please remove "Roadmap"

### ISSUE THREAD

**Issue by PaulaKvedaras** [scrumatscale/official-guide#59]
The world Roadmap is only used once in the guide, and it sounds IT.

**Comment by sbeaumont** [comment]
We just had a discussion during the S@S Train the Trainer: Chris, Carol, Omar and myself agree that the word, and even the whole line could be removed. Furthermore we think that the whole section of bullets can use a review since it's somewhat artifact and activity heavy. It can use some descriptions that describe desired outcomes.

**Comment by jeffsutherland** [comment]
The Guide has been changed so that the Product Owner is responsible for the Release Plan and a forecast of future features that will be developed beyond the release plan (sometimes called a roadmap). Venture companies cannot effectively sell their products without a forecast even though everyone knows the forecast will change.
