### ISSUE TITLE
S@S Guide Needs to be Harmonized with ScrumPlop MetaScrum Pattern

### ISSUE THREAD

**Issue by jeffsutherland** [scrumatscale/official-guide#64]
The Metascrum is a meeting of the Product Owner team with stakeholders to align and lock down the prioitized backlog (strategy, resources, and implementation). See the ScrumPlop pattern. This is not properly reflected in the Scrum Guide.

**Comment by jeffsutherland** [comment]
We have most of what is needed in the S@S Guide. The two pieces that need to change are to remove the comment on Product Backlog Refinement. The executive team members in the Metascrum want to see a ready backlog and decide whether they agree or not in 90 minutes or less. The second piece is the primary goal is get agreement on the strategy, the resources, and the executive and that this agreement will not change until the next MetaScrum. This still allows back room politics but does not allow backroom decision making. All decisions are transparent.

**Comment by jeffsutherland** [comment]
A related issue is that the Scrum of Scrum PO is the Chief Product Owner and the backlog to be delivered at the end of each sprint includes at least one improvement generated from the impediment backlog.

**Comment by DanielMezick** [comment]
One additional concern that probably belongs here is an inconsistency of terminology use with respect to the term 'MetaScrum'. 

In the Guide's description of the Product Owner Cycle, the term "MetaScrum" clearly refers to an Event. But then the term [Executive MetaScrum] is used to refer to a Role of type Team. This inconsistency is an impediment to overall Guide clarity. 

One possible resolution is to consistently use the term [Product Owner Team] all the way up to the Executive level, i.e, [Executive Product Owner Team] instead of the inconsistent & current term, [Executive MetaScrum].

**Comment by jeffsutherland** [comment]
The Guide has been updated to specify the MetaScrum event and the Executive Metascrum Team which is the team of Product Owners plus business owners.

**Comment by DanielMezick** [comment]
Greetings,

The language is still confusing as the term [MetaScrum] applied to both a team and a meeting.

I respectfully suggest replacing the term 'Executive MetaScrum' with another term that has zero potential for creating confusion, for example "Executive Product Team" (abbreviated "EPT" as the clear non-ambiguous counterpart to the "EAT"). 


Daniel Mezick
Phone: 203 915 7248
Bio & Contact Info: http://www.DanielMezick.com <http://www.danielmezick.com/>
Latest Book: http://www.InvitingLeadership.com <http://www.invitingleadership.com/>

Business Agility Leadership event May 14-15 Boston: 
The Open Leadership Symposium <https://openleadershipnetwork.com/>

**Comment by jeffsutherland** [comment]
There have been many changes to the guide made that address this issue. I'm closing it for now.
